apiVersion: v1
kind: PhJob
metadata:
  name: ntmcal
  description: "pharbers job description"
  labels:
    name: ntmcal
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 10.0
    code: phmain.py
    config: phconf.yaml
    args:      
      - key: job_name
        value: ntmcal
      - key: path_prefix
        value: s3a://ph-max-auto/2020-08-11/NTM/runs
      - key: provider
        value: NTM
      - key: proposal_id
        value: 60505e4b81ef2c5db38b4699
      - key: project_id
        value: rR9lwp8e55q9izZdHdQZ
      - key: period_id
        value: o8mpVPkJTVrUFfgk6KR-
      - key: phase
        value: 1
      - key: weight_path
        value: s3a://ph-max-auto/2020-08-11/NTM/data/Weightages.csv
      - key: curves_path
        value: s3a://ph-max-auto/2020-08-11/NTM/data/Curves.csv
      - key: depend_job_names_keys
        value: 
          - ntmpull#pull_result#cal_path
    outputs:
      - key: cal_result
        value: cal_result
