apiVersion: v1
kind: PhJob
metadata:
  name: job1
  description: "pharbers job description"
  labels:
    name: job1
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 10.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: input
        value: "zhang min is good boy !"
    outputs:
      - key: output_path_job1
        value: "111 "


