apiVersion: v1
kind: PhJob
metadata:
  name: job6_max_city
  description: "pharbers job description"
  labels:
    name: job6_max_city
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: max_path
        value: 's3a://ph-max-auto/v0.0.1-2020-06-08/'
      - key: project_name
        value: 'Empty'
      - key: time_left
        value: 'Empty'
      - key: time_right
        value: 'Empty'
      - key: left_models
        value: 'Empty'
      - key: left_models_time_left
        value: 'Empty'
      - key: right_models
        value: 'Empty'
      - key: right_models_time_right
        value: 'Empty'
      - key: all_models
        value: 'Empty'
      - key: if_others
        value: 'False'
      - key: out_path
        value: 's3a://ph-max-auto/v0.0.1-2020-06-08/'
      - key: out_dir
        value: 'Empty'
      - key: need_test
        value: '0'
      - key: minimum_product_columns
        value: 'Brand, Form, Specifications, Pack_Number, Manufacturer'
      - key: minimum_product_sep
        value: '|'
      - key: minimum_product_newname
        value: 'min1'
      - key: if_two_source
        value: 'False'
      - key: hospital_level
        value: 'False'
      - key: bedsize
        value: 'True'
      - key: id_bedsize_path
        value: 'Empty'
    outputs:
      - key: c
        value: 'abc'
      - key: d
        value: 'def'



