apiVersion: v1
kind: PhJob
metadata:
  name: job1
  description: "pharbers job description"
  labels:
    name: job1
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 10.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: path_chc
        value: s3a://ph-max-auto/2020-08-11/data_matching/refactor/data/CHC/*
      - key: path_standard
        value: s3a://ph-stream/common/public/prod/0.0.21
    outputs:
      - key: output_path_job1
        value: "111 "


