apiVersion: v1
kind: PhJob
metadata:
  name: email
  description: "水位监控邮件"
  labels:
    name: email
    runtime: python3
    command: script
spec:
  containers:
    repository: local
    runtime: python3
    command: script
    timeout: 10.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: email
        value: pqian@pharbers.com
      - key: subject
        value: 监控
      - key: content_type
        value: text/plain
      - key: content
        value: default
    outputs:
      - key: c
        value: "abc"



