apiVersion: v1
kind: PhJob
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf.yaml
    args:
      - key: input_path
        value: s3a://ph-stream/common/public/mole_human_replace/0.0.1
      - key: output_path
        value: s3a://ph-platform/2020-08-10/datamart/standard/dimensions/alias/v20201001_20201015_1
    outputs:
      - key: a
        value: abcde
      - key: b
        value: 6789



