apiVersion: v1
kind: PhDag
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  description: "Output Potential Universe"
  start_date: 1 # if you don't understand, don't touch it
  schedule_interval: "None" # if you don't understand, don't touch it
  dag_timeout: 60 # minutes
  email: ['airflow@example.com']
  email_on_failure: False
  email_on_retry: False
  retries: 1
  retry_delay: "minutes=5"
  owner: jqyu
  dag_id: output_pot_universe
  dag_tag: output_pot_universe
  jobs:
    - name: datamart_output_hosp_pot
      command: python3
  linkage: "datamart_output_hosp_pot"
