apiVersion: v1
kind: PhJob
metadata:
  name: job2_product_mapping
  description: "pharbers job description"
  labels:
    name: job2_product_mapping
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: project_name
        value: 'Takeda'
      - key: minimum_product_columns
        value: 'Brand, Form, Specifications, Pack_Number, Manufacturer'
      - key: minimum_product_sep
        value: '|'
      - key: minimum_product_newname
        value: 'min1'
      - key: need_cleaning_cols
        value: 'Molecule, Brand, Form, Specifications, Pack_Number, Manufacturer, min1, Route, Corp'
      - key: out_path
        value: 's3://ph-platform/2020-11-11/etl/temporary_files/'
      - key: run_id
        value: 'run_id_max_test'
      - key: owner
        value: 'Airflow'
      - key: g_input_version
        value: '{"prod_mapping":"202103_u0079u0079u0077"}'
    outputs:
      - key: g_out_table
        value: 'product_mapping_out'
      - key: g_need_clean_table
        value: 'need_cleaning'



