apiVersion: v1
kind: PhJob
metadata:
  name: delivery
  description: "pharbers job description"
  labels:
    name: delivery
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: project_name
        value: 'Empty'
      - key: time_left
        value: 'Empty'
      - key: time_right
        value: 'Empty'
      - key: out_dir
        value: 'Empty'
      - key: extract_path
        value: 's3://ph-stream/common/public/max_result/0.0.5/rawdata_standard'
      - key: max_path
        value: 's3://ph-max-auto/v0.0.1-2020-06-08/'
    outputs:
      - key: c
        value: 'abc'
      - key: d
        value: 'def'



