apiVersion: v1
kind: PhJob
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf-20200826.yaml
    args:
      - key: input_path
        value: s3a://ph-stream/common/public/prod/17
      - key: output_path
        value: s3a://ph-stream/common/public/prod/0.0.15
      - key: table_name
        value: prod
    outputs:
      - key: a
        value: abcde
      - key: b
        value: 6789