apiVersion: v1
kind: PhJob
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf.yaml
    args:
      - key: input_file_format
        value: parquet
      - key: input_path
        value: 'not_null'
      - key: output_file_format
        value: parquet
      - key: output_path
        value: 'not_null'
      - key: save_mode
        value: append
      - key: table_name
        value: 'not_null'
    outputs:
      - key: a
        value: abcde
      - key: b
        value: 6789