apiVersion: v1
kind: PhJob
metadata:
  name: hospital_mapping
  description: "pharbers job description"
  labels:
    name: hospital_mapping
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: g_project_name
        value: 'Empty'
      - key: if_others
        value: 'False'
      - key: g_out_dir
        value: 'Empty'
      - key: g_max_path
        value: 's3a://ph-max-auto/v0.0.1-2020-06-08/'
      - key: g_base_path
        value: 's3a://ph-max-auto/2020-08-11/data_matching/refactor/data/MAX'
    outputs:
      - key: g_hospital_mapping_out
        value: 'hospital_mapping_out'



