apiVersion: v1
kind: PhJob
metadata:
  name: job3_2_original_range_raw
  description: "pharbers job description"
  labels:
    name: job3_2_original_range_raw
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: project_name
        value: 'Takeda'
      - key: model_month_right
        value: '202012'
      - key: max_month
        value: '0'
      - key: year_missing
        value: '0'
      - key: current_year
        value: '2021'
      - key: first_month
        value: '1'
      - key: current_month
        value: '3'
      - key: if_others
        value: 'False'
      - key: monthly_update
        value: 'True'
      - key: if_add_data
        value: 'True'
      - key: out_path
        value: 's3://ph-platform/2020-11-11/etl/temporary_files/'
      - key: run_id
        value: 'run_id_max_test_2'
      - key: owner
        value: 'Airflow'
      - key: g_database_temp
        value: 'phdatatemp'
      - key: g_database_input
        value: 'phdatacat'
    outputs:
      - key: g_out_adding_data
        value: 'adding_data'
      - key: g_out_new_hospital
        value: 'new_hospital'
      - key: g_out_raw_data_adding_final
        value: 'raw_data_adding_final'



