apiVersion: v1
kind: PhJob
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  containers:
    repository: local
    code: phmain.py
    config: phconf.yaml
    args:
      - key: max_path
        value: "s3a://ph-max-auto/v0.0.1-2020-06-08/"
      - key: project_name
        value: "Empty"
      - key: model_month_left
        value: "0"
      - key: model_month_right
        value: "0"
      - key: if_others
        value: "False"
      - key: current_year
        value: "2020"
      - key: current_month
        value: "Empty"
      - key: paths_foradding
        value: "s3a://ph-max-auto/v0.0.1-2020-06-08/AZ_Sanofi/Not_arrived202001.csv, s3a://ph-max-auto/v0.0.1-2020-06-08/AZ_Sanofi/Not_arrived201912.csv, s3a://ph-max-auto/v0.0.1-2020-06-08/AZ_Sanofi/Unpublished2020.csv"
      - key: not_arrived_path
        value: "Empty"
      - key: unpublished_path
        value: "s3a://ph-max-auto/v0.0.1-2020-06-08/Common_files/Unpublished2020.csv"
      - key: panel_for_union
        value: "Empty"
      - key: monthly_update
        value: "False"
      - key: out_path
        value: "s3a://ph-max-auto/v0.0.1-2020-06-08/"
      - key: out_dir
        value: "Empty"  
      - key: need_test
        value: 0
    outputs:
      - key: a
        value: abcde
      - key: b
        value: 6789

