apiVersion: v1
kind: PhJob
metadata:
  name: extract_data
  description: "pharbers job description"
  labels:
    name: extract_data
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: max_path
        value: 's3://ph-max-auto/v0.0.1-2020-06-08/'
      - key: extract_path
        value: 's3://ph-stream/common/public/max_result/0.0.5/'
      - key: out_path
        value: 's3://ph-stream/common/public/max_result/0.0.5/extract_data_out'
      - key: extract_file
        value: 'Empty'
      - key: time_left
        value: 'Empty'
      - key: time_right
        value: 'Empty'
      - key: molecule
        value: 'Empty'
      - key: molecule_sep
        value: 'Empty'
      - key: atc
        value: 'Empty'
      - key: project
        value: 'Empty'
      - key: doi
        value: 'Empty'
      - key: out_suffix
        value: 'Empty'
      - key: data_type
        value: 'max'
      - key: market_define
        value: 'Empty'
    outputs:
      - key: c
        value: 'abc'
      - key: d
        value: 'def'



