apiVersion: v1
kind: PhJob
metadata:
  name: model_training
  description: "pharbers job description"
  labels:
    name: model_training
    runtime: python3
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf.yaml
    command: submit
    timeout: 800
    args:
      - key: job_name
        value: cleaning_data_model_training
      - key: path_prefix
        value: s3a://ph-max-auto/2020-08-11/data_matching/refactor/runs
      - key: final_prefix
        value: s3a://ph-max-auto/2020-08-11/data_matching/refactor/results
      - key: input_model_path
        value: s3a://ph-max-auto/2020-08-11/data_matching/refactor/results/2021-01-17_22-54-55/Models
      - key: Training_Model
        value: None
      - key: depend_job_names_keys
        value: 
          - labeling_with_crossed_data#label_result#input
    outputs:
      - key: model_result
        value: model_result
      - key: model_validate
        value: model_validate
      - key: final_model
        value: Models
      - key: data_of_features
        value: data_of_features
