apiVersion: v1
kind: PhDag
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  description: "Auto Transform Datamart"
  start_date: 1 # if you don't understand, don't touch it
  schedule_interval: "None" # if you don't understand, don't touch it
  dag_timeout: 60 # minutes
  email: ['airflow@example.com']
  email_on_failure: False
  email_on_retry: False
  retries: 1
  retry_delay: "minutes=5"
  owner: clock
  dag_id: Auto_Datamart
  dag_tag: Auto_Datamart
  jobs:
    - name: datamart_dim_mnfs
      command: python3
    - name: datamart_dim_prod
      command: python3
    - name: datamart_dim_hosp
      command: python3
    - name: datamart_dim_alias
      command: python3
    - name: datamart_dim_clean_rules
      command: python3
    - name: datamart_fact_chc_prod
      command: python3
    - name: datamart_fact_chc_hosp
      command: python3
    - name: datamart_fact_chc_date
      command: python3
    - name: datamart_fact_chc_etc
      command: python3
    - name: datamart_fact_chc
      command: python3
    - name: datamart_fact_cpa_prod
      command: python3
    - name: datamart_fact_cpa_hosp
      command: python3
    - name: datamart_fact_cpa_date
      command: python3
    - name: datamart_fact_cpa_etc
      command: python3
    - name: datamart_fact_cpa
      command: python3
    - name: datamart_fact_max_result_prod
      command: python3
    - name: datamart_fact_max_result_hosp
      command: python3
    - name: datamart_fact_max_result_etc
      command: python3
    - name: datamart_fact_max_result
      command: python3
  linkage: "[datamart_dim_mnfs, datamart_dim_prod, datamart_dim_hosp, datamart_dim_alias, datamart_dim_clean_rules]"
