apiVersion: v1
kind: PhJob
metadata:
  name: job5_max_weight
  description: "pharbers job description"
  labels:
    name: job5_max_weight
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: project_name
        value: 'Takeda'
      - key: if_base
        value: 'False'
      - key: time_left
        value: '202101'
      - key: time_right
        value: '202103'
      - key: left_models
        value: 'Empty'
      - key: left_models_time_left
        value: 'Empty'
      - key: right_models
        value: 'Empty'
      - key: right_models_time_right
        value: 'Empty'
      - key: all_models
        value: 'TK1'
      - key: universe_choice
        value: 'Empty'
      - key: use_d_weight
        value: 'Empty'
      - key: out_path
        value: 's3://ph-platform/2020-11-11/etl/temporary_files/'
      - key: run_id
        value: 'run_id_max_test'
      - key: owner
        value: 'Airflow'
      - key: g_input_version
        value: '{"weight":{"weight":"20210624_u0079u0079u0077", "weight_default":"20210624_u0079u0079u0077"}, "universe_base":"2020_u0079u0079u0077", "factor":{"TK1":"20210623_u0079u0079u0077"}, "universe_outlier":{"TK1":"20210623_u0079u0079u0077"}}'
      - key: g_database_temp
        value: 'phdatatemp'
      - key: g_database_input
        value: 'phdatacat'
    outputs:
      - key: a
        value: 'abcde'
      - key: b
        value: '6789'



