apiVersion: v1
kind: PhJob
metadata:
  name: job5_max_weight
  description: "pharbers job description"
  labels:
    name: job5_max_weight
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: project_name
        value: 'Takeda'
      - key: if_base
        value: 'False'
      - key: time_left
        value: '202101'
      - key: time_right
        value: '202103'
      - key: all_models
        value: 'TK1'
      - key: universe_choice
        value: 'Empty'
      - key: use_d_weight
        value: 'Empty'
      - key: if_others
        value: 'False'
      - key: out_path
        value: 's3://ph-platform/2020-11-11/etl/temporary_files/'
      - key: run_id
        value: 'run_id_max_test'
      - key: owner
        value: 'Airflow'
      - key: g_database_temp
        value: 'phdatatemp'
      - key: g_database_input
        value: 'phdatacat'
    outputs:
      - key: g_out_max
        value: 'max_result_raw'



