apiVersion: v1
kind: PhJob
metadata:
  name: job7_max_standard
  description: "pharbers job description"
  labels:
    name: job7_max_standard
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: extract_path
        value: 's3://ph-platform/2020-11-11/etl/extract/max_standard'
      - key: project_name
        value: 'Takeda'
      - key: out_path
        value: 's3://ph-platform/2020-11-11/etl/temporary_files/'
      - key: run_id
        value: 'run_id_max_test_2'
      - key: owner
        value: 'Airflow'
      - key: g_input_version
        value: '{"prod_mapping":"202103_u0079u0079u0077", "product_map_all_atc":"20210617", "master_data_map":"20210623_u0079u0079u0077", "province_city_mapping_common":"20210623_u0079u0079u0077"}'
      - key: g_database_temp
        value: 'phdatatemp'
      - key: g_database_input
        value: 'phdatacat'
    outputs:
      - key: g_out_max_standard
        value: 'max_result_standard'
      - key: g_out_max_standard_brief
        value: 'max_result_standard_brief'



