apiVersion: v1
kind: PhJob
metadata:
  name: job7_raw_standard
  description: "pharbers job description"
  labels:
    name: job7_raw_standard
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: extract_path
        value: 's3://ph-platform/2020-11-11/etl/extract/'
      - key: project_name
        value: 'Takeda'
      - key: if_two_source
        value: 'True'
      - key: minimum_product_sep
        value: '|'
      - key: minimum_product_columns
        value: 'Brand, Form, Specifications, Pack_Number, Manufacturer'
      - key: g_for_extract
        value: 'True'
      - key: out_path
        value: 's3://ph-platform/2020-11-11/etl/temporary_files/'
      - key: run_id
        value: 'run_id_max_test'
      - key: owner
        value: 'Airflow'
      - key: g_database_temp
        value: 'phdatatemp'
      - key: g_database_input
        value: 'phdatacat'
    outputs:
      - key: g_out_raw_standard
        value: 'raw_data_standard'
      - key: g_out_raw_standard_brief
        value: 'raw_data_standard_brief'



