apiVersion: v1
kind: PhJob
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf.yaml
    args:
      - key: max_path
        value: 's3a://ph-max-auto/v0.0.1-2020-06-08/'
      - key: project_name
        value: 'Empty'
      - key: outdir
        value: 'Empty'
      - key: history_outdir
        value: 'Empty'
      - key: raw_data_path
        value: 'Empty'
      - key: if_two_source
        value: 'False'
      - key: cut_time_left
        value: '0'
      - key: cut_time_right
        value: '0'
      - key: if_union
        value: 'True'
      - key: test
        value: 'False'
      - key: auto_max
        value: 'True'
    outputs:
      - key: a
        value: abcde
      - key: b
        value: 6789
