apiVersion: v1
kind: PhJob
metadata:
  name: get_correct_data
  description: "pharbers job description"
  labels:
    name: get_correct_data
    runtime: python3
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf.yaml
    timeout: 800
    command: submit
    args:
      - key: job_name
        value: get_correct_data
      - key: path_prefix
        value: s3a://ph-max-auto/2020-08-11/data_matching/refactor/runs
      - key: depend_job_names_keys
        value: 
          - cleaning_data_normalization#cleaning_result#cleaning
          - standard_data_normalization#standard_result#standard
      - key: g_partitions_num
        value: 16
    outputs:
      - key: output_correct_result
        value: output_correct_result
