apiVersion: v1
kind: PhJob
metadata:
  name: effectiveness_adjust_mnf
  description: "pharbers job description"
  labels:
    name: effectiveness_adjust_mnf
    runtime: python3
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf.yaml
    args:
      - key: job_name
        value: effectiveness_adjust_mnf
      - key: path_prefix
        value: s3a://ph-max-auto/2020-08-11/data_matching/refactor/runs
      - key: word_dict_encode_path
        value: s3a://ph-max-auto/2020-08-11/data_matching/refactor/data/WORD_DIC/0.0.12
      - key: lexicon_path
        value: s3a://ph-max-auto/2020-08-11/data_matching/refactor/data/LEXICON/0.0.2
      - key: depend_job_names_keys
        value: 
          - effectiveness_with_jws#effective_result#input
      - key: g_repartition_shared
        value: 10
    outputs:
      - key: mnf_adjust_result
        value: mnf_adjust_result
      - key: mnf_adjust_mid
        value: mnf_adjust_mid
