apiVersion: v1
kind: PhJob
metadata:
  name: check_prepare
  description: "pharbers job description"
  labels:
    name: check_prepare
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 1000.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: g_input_version
        value: '{"cpa_gyc_hospital_map":"20210712_u0079u0079u0077", "ims_flat_files":{"cn_IMS_Sales_Fdata":"cn_IMS_Sales_Fdata_202103_1","cn_mol_lkp":"cn_mol_lkp_202103_1","cn_mol_ref":"cn_mol_ref_202103_1","IMS_mapping_citycode":"IMS_mapping_citycode"}}'
      - key: project_name
        value: 'Takeda'
      - key: out_path
        value: 's3://ph-platform/2020-11-11/etl/temporary_files/'
      - key: run_id
        value: 'run_id_max_test'
      - key: owner
        value: 'Airfolw'
      - key: g_database_temp
        value: 'phdatatemp'
      - key: g_database_input
        value: 'phdatacat'
    outputs:
      - key: g_out_ims
        value: 'ims_sales_info'



