apiVersion: v1
kind: PhDag
metadata:
  name: market_level
  description: "pharbers job -- market_level"
  labels:
    name: market_level
    runtime: python3
spec:
  description: "A Max Auto Job Example"
  start_date: 1 # if you don't understand, don't touch it
  schedule_interval: "None" # if you don't understand, don't touch it
  dag_timeout: 60 # minutes
  email: ['airflow@example.com']
  email_on_failure: False
  email_on_retry: False
  retries: 1
  retry_delay: "minutes=5"
  owner: zm
  dag_id: market_level
  dag_tag: market_level
  jobs:
    - name: market_level
      command: python3
  linkage:
    - "market_level"

