apiVersion: v1
kind: PhJob
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf.yaml
    args:
      - key: prod_renamed_path
        value: "s3a://ph-max-auto/2020-08-11/BPBatchDAG/check_prod_renamed"
      - key: in_hr_path
        value: "s3a://ph-stream/common/public/human_replace/0.0.14"
      # - key: prod_min_key_lst
      #   value: ["MOLE_NAME_EN", "MOLE_NAME_CH", "PROD_NAME_CH", "SPEC", "DOSAGE", "PACK", "MNF_NAME_CH", "MNF_NAME_EN", "PACK_ID"]
      - key: out_path
        value: "s3a://ph-max-auto/2020-08-11/BPBatchDAG/pfizer_check/0.0.1"
    outputs:
      - key: a
        value: abcde
      - key: b
        value: 6789

