apiVersion: v1
kind: PhJob
metadata:
  name: extract_data
  description: "pharbers job description"
  labels:
    name: extract_data
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: time_left
        value: 'Empty'
      - key: time_right
        value: 'Empty'
      - key: molecule
        value: 'Empty'
      - key: molecule_sep
        value: 'Empty'
      - key: atc
        value: 'Empty'
      - key: project
        value: 'Empty'
      - key: doi
        value: 'Empty'
      - key: out_suffix
        value: 'Empty'
      - key: data_type
        value: 'max'
      - key: market_define
        value: 'Empty'
      - key: out_path
        value: 's3://ph-platform/2020-11-11/etl/extract/extract_data_out'
      - key: run_id
        value: 'extract_test_0723'
      - key: owner
        value: 'ywyuan'
      - key: g_input_version
        value: '{"project_rank":"project_rank_20210721", "market_define":"market_define_20210720", "project_for_extract":"project_for_extract_20210721"}'
      - key: g_database_input
        value: 'phdatacat'
      - key: g_database_result
        value: 'phresult'
    outputs:
      - key: c
        value: 'abc'
      - key: d
        value: 'def'



