apiVersion: v1
kind: PhJob
metadata:
  name: update_table
  description: "pharbers job description"
  labels:
    name: update_table
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 1000.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: g_path
        value: 's3://ph-platform/2020-11-11/etl/temporary_files/max_result_standard_brief/version=Max_u0079u0079u0077_2021-07-19_17-42-10/provider=Astellas/owner=Airflow'
      - key: g_update
        value: '202101,202102'
      - key: g_database
        value: 'phresult'
      - key: g_table
        value: 'max_result'
    outputs:
      - key: c
        value: 'abc'
      - key: d
        value: 'def'



