apiVersion: v1
kind: PhJob
metadata:
  name: max_standard
  description: "pharbers job description"
  labels:
    name: max_standard
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: g_path_max
        value: s3a://ph-max-auto/v0.0.1-2020-06-08/
      - key: g_path_extract
        value: s3a://ph-stream/common/public/max_result/0.0.5/max_standard
      - key: g_project_name
        value: Empty
      - key: g_out_dir
        value: Empty
      - key: g_dag_name
        value: Max
      - key: g_run_id
        value: max_test_beida_202012
      - key: g_depend_job_names_keys
        value: ["max_city#max_city_result#max_city_result"]
    outputs:
      - key: a
        value: abcde
      - key: b
        value: 6789



