apiVersion: v1
kind: PhJob
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf.yaml
    args:
      - key: in_prod_path
        value: "s3a://ph-stream/common/public/prod/0.0.17"
      - key: in_hr_path
        value: "s3a://ph-stream/common/public/human_replace/0.0.14"
      - key: out_path
        value: "s3a://ph-max-auto/2020-08-11/BPBatchDAG/azsanofi_check/0.0.11"
      - key: pk  # cpa和prod join的主键
        # value: "MANUFACTURER_NAME"
        # value: "MOLE_NAME"
        value: "PRODUCT_NAME"
      - key: mnf_name_mapping
        value: "s3a://ph-max-auto/2020-08-11/BPBatchDAG/mnf_name_mapping"
    outputs:
      - key: a
        value: abcde
      - key: b
        value: 6789

