apiVersion: v1
kind: PhJob
metadata:
  name: job3
  description: "pharbers job description"
  labels:
    name: job3
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 10.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: input
        value: "abc"
    outputs:
      - key: output
        value: "abc"



