apiVersion: v1
kind: PhJob
metadata:
  name: create_table
  description: "pharbers job description"
  labels:
    name: create_table
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 1000.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: g_database_result
        value: 'phresult'
      - key: g_out_table
        value: 'max_result'
      - key: filetype
        value: 'all'
      - key: g_path
        value: 's3://ph-platform/2020-11-11/etl/temporary_files/max_result_standard/version=Max_u0079u0079u0077_2021-07-19_16-07-05/provider=Astellas/owner=Airflow, s3://ph-platform/2020-11-11/etl/temporary_files/max_result_standard/version=Max_u0079u0079u0077_2021-07-19_16-07-25/provider=AZ/owner=Airflow, s3://ph-platform/2020-11-11/etl/temporary_files/max_result_standard/version=Max_u0079u0079u0077_2021-07-19_16-08-22/provider=Gilead/owner=Airflow, s3://ph-platform/2020-11-11/etl/temporary_files/max_result_standard/version=Max_u0079u0079u0077_2021-07-19_16-08-29/provider=Mylan/owner=Airflow, s3://ph-platform/2020-11-11/etl/temporary_files/max_result_standard/version=Max_u0079u0079u0077_2021-07-19_16-08-36/provider=Pfizer/owner=Airflow, s3://ph-platform/2020-11-11/etl/temporary_files/max_result_standard/version=Max_u0079u0079u0077_2021-07-19_16-12-41/provider=Sankyo/owner=Airflow, s3://ph-platform/2020-11-11/etl/temporary_files/max_result_standard/version=Max_u0079u0079u0077_2021-07-19_16-12-45/provider=Sanofi/owner=Airflow, s3://ph-platform/2020-11-11/etl/temporary_files/max_result_standard/version=Max_u0079u0079u0077_2021-07-19_16-13-26/provider=Servier/owner=Airflow, s3://ph-platform/2020-11-11/etl/temporary_files/max_result_standard/version=Max_u0079u0079u0077_2021-07-19_16-13-47/provider=Tide/owner=Airflow, s3://ph-platform/2020-11-11/etl/temporary_files/max_result_standard/version=Max_u0079u0079u0077_2021-07-19_16-13-56/provider=XLT/owner=Airflow, s3://ph-platform/2020-11-11/etl/temporary_files/max_result_standard/version=Max_u0079u0079u0077_2021-07-19_16-14-01/provider=京新/owner=Airflow, s3://ph-platform/2020-11-11/etl/temporary_files/max_result_standard/version=Max_u0079u0079u0077_2021-07-19_16-14-08/provider=康哲/owner=Airflow, s3://ph-platform/2020-11-11/etl/temporary_files/max_result_standard/version=Max_u0079u0079u0077_2021-07-19_16-14-13/provider=汇宇/owner=Airflow'
    outputs:
      - key: c
        value: 'abc'
      - key: d
        value: 'def'



