apiVersion: v1
kind: PhDag
metadata:
  name: Auto_Max_yuanyw
  description: "pharbers job description"
  labels:
    name: Auto_Max_yuanyw
spec:
  description: "A Max Auto Job Example"
  start_date: 1 # if you don't understand, don't touch it
  schedule_interval: "None" # if you don't understand, don't touch it
  email: ['airflow@example.com']
  email_on_failure: False
  email_on_retry: False
  retries: 0
  retry_delay: "minutes=5"
  owner: ywyuan
  dag_id: Auto_Max_yuanyw
  dag_tag: Max
  dag_timeout:  # minutes
  jobs:
    - name: job1_hospital_mapping
    - name: job2_product_mapping
    - name: job3_1_data_adding
    - name: Max.job3_2_data_adding
    - name: job4_panel
    - name: job5_max_weight
    - name: Max.job6_max_city
    - name: job7_max_standard
    - name: job7_raw_standard
    - name: Max.check
    - name: Max.delivery
    - name: Rawdata.delivery
  linkage:
    - "job1_hospital_mapping >> job2_product_mapping >> job3_1_data_adding >> Max.job3_2_data_adding >> job4_panel >> job5_max_weight >> Max.job6_max_city >> [Max.check, job7_max_standard, job7_raw_standard]"
    - "job7_max_standard >> Max.delivery"
    - "job7_raw_standard >> Rawdata.delivery"

