apiVersion: v1
kind: PhJob
metadata:
  name: check_lu
  description: "pharbers job description"
  labels:
    name: check_lu
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: max_path
        value: 's3://ph-max-auto/v0.0.1-2020-06-08/'
      - key: out_path
        value: 's3://ph-max-auto/v0.0.1-2020-06-08/'
      - key: project_name
        value: 'Empty'
      - key: if_base
        value: 'False'
      - key: time_left
        value: 'Empty'
      - key: time_right
        value: 'Empty'
      - key: left_models
        value: 'Empty'
      - key: left_models_time_left
        value: 'Empty'
      - key: right_models
        value: 'Empty'
      - key: right_models_time_right
        value: 'Empty'
      - key: all_models
        value: 'Empty'
      - key: universe_choice
        value: 'Empty'
      - key: if_others
        value: 'False'
      - key: out_dir
        value: 'Empty'
    outputs:
      - key: c
        value: 'abc'
      - key: d
        value: 'def'



