apiVersion: v1
kind: PhDag
metadata:
  name: Auto_data_match_chc
  description: "auto_data_match_chc"
  labels:
    name: Auto_data_match_chc
spec:
  description: "A Max Auto Job Example"
  start_date: 1 # if you don't understand, don't touch it
  schedule_interval: "None" # if you don't understand, don't touch it
  email: ['airflow@example.com']
  email_on_failure: False
  email_on_retry: False
  retries: 1
  retry_delay: "minutes=5"
  owner: mzhang
  dag_id: Auto_data_match_chc
  dag_tag: default
  dag_timeout: 600 # minutes
  jobs:
    - name: data_matching.crossing
    - name: data_matching.training
    - name: data_matching.training_validate
  linkage:
    - "data_matching.crossing >> data_matching.training >> data_matching.training_validate"

