apiVersion: v1
kind: PhJob
metadata:
  name: job2
  description: "pharbers job description"
  labels:
    name: job2
    runtime: python3
spec:
  containers:
    repository: local
    runtime: python3
    command: "submit"
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: max_path
        value: "s3a://ph-max-auto/v0.0.1-2020-06-08/"
      - key: project_name
        value: "Empty"
      - key: market_city_brand
        value: "Empty"
      - key: lmda
        value: '0.001'
      - key: learning_rate
        value: '100'
      - key: max_iteration
        value: '10000'
      - key: gradient_type
        value: 'both'
      - key: test
        value: 'False'
    outputs:
      - key: c
        value: abcde
      - key: d
        value: 6789



