apiVersion: v1
kind: PhJob
metadata:
  name: gradient_descent
  description: "pharbers job description"
  labels:
    name: gradient_descent
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: max_path
        value: 's3://ph-max-auto/v0.0.1-2020-06-08/'
      - key: project_name
        value: 'Empty'
      - key: market_city_brand
        value: 'Empty'
      - key: lmda
        value: '0.001'
      - key: learning_rate
        value: '100'
      - key: max_iteration
        value: '10000'
      - key: gradient_type
        value: 'both'
      - key: test
        value: 'False'
      - key: year_list
        value: 'Empty'
    outputs:
      - key: c
        value: 'abc'
      - key: d
        value: 'def'



