apiVersion: v1
kind: PhJob
metadata:
  name: cross_join_cutting
  description: "pharbers job description"
  labels:
    name: cross_join_cutting
    runtime: python3
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf.yaml
    args:
      - key: job_name
        value: cross_join_cutting
      - key: path_prefix
        value: s3a://ph-max-auto/2020-08-11/data_matching/refactor/runs
      - key: depend_job_names_keys
        value: 
          - cleaning_data_normalization#cleaning_result#cleaning
          - standard_data_normalization#standard_result#standard
      - key: g_partitions_num
        value: 1600
    outputs:
      - key: cross_result
        value: cross_result
      - key: cross_drop
        value: cross_drop
