apiVersion: v1
kind: PhJob
metadata:
  name: max_city
  description: "pharbers job description"
  labels:
    name: max_city
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: g_project_name
        value: 'Empty'
      - key: g_minimum_product_columns
        value: 'BRAND, FORM, SPECIFICATIONS, PACK_NUMBER, MANUFACTURER'
      - key: g_minimum_product_sep
        value: '|'
      - key: g_minimum_product_newname
        value: 'MIN'
      - key: g_if_two_source
        value: 'False'
      - key: g_hospital_level
        value: 'False'
      - key: g_bedsize
        value: 'True'
      - key: p_id_bedsize
        value: 'Empty'
      - key: g_monthly_update
        value: 'Empty'
      - key: g_year
        value: 'Empty'
      - key: g_month
        value: 'Empty'
      - key: g_market
        value: 'Empty'
      - key: depend_job_names_keys
        value: '["max_weight#max_weight_result#max_weight_result"]'
      - key: g_max_path
        value: 's3a://ph-max-auto/v0.0.1-2020-06-08/'
      - key: g_out_dir
        value: 'Empty'
      - key: dag_name
        value: 'Max'
      - key: run_id
        value: 'max_test_beida_202012'
    outputs:
      - key: g_max_result_city
        value: 'max_city_result'



