apiVersion: v1
kind: PhJob
metadata:
  name: extract_report
  description: "pharbers job description"
  labels:
    name: extract_report
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: out_suffix
        value: 'Empty'
      - key: data_type
        value: 'max'
      - key: atc
        value: 'Empty'
      - key: molecule
        value: 'Empty'
      - key: molecule_sep
        value: 'Empty'
      - key: out_path
        value: 's3://ph-platform/2020-11-11/etl/extract/extract_data_out'
      - key: run_id
        value: 'extract_test_0723'
      - key: owner
        value: 'ywyuan'
      - key: g_input_version
        value: '{"ims_mapping":"ims_mapping_202007", "cn_IMS_Sales_Fdata":"cn_IMS_Sales_Fdata_202007", "product_map_all_ATC":"20210617", "master_data_map":"20210623_u0079u0079u0077"}'
      - key: g_database_input
        value: 'phdatacat'
      - key: g_database_result
        value: 'phresult'
    outputs:
      - key: c
        value: 'abc'
      - key: d
        value: 'def'



