apiVersion: v1
kind: PhJob
metadata:
  name: job3_1_price_city
  description: "pharbers job description"
  labels:
    name: job3_1_price_city
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: project_name
        value: 'Takeda'
      - key: out_path
        value: 's3://ph-platform/2020-11-11/etl/temporary_files/'
      - key: run_id
        value: 'run_id_max_test_2'
      - key: owner
        value: 'Airflow'
      - key: g_input_version
        value: '{"poi":"20210623_u0079u0079u0077", "not_arrived":"202103_u0079u0079u0077, 202012_u0079u0079u0077, 201912_u0079u0079u0077, 201812_u0079u0079u0077","published":"2017_u0079u0079u0077, 2018_u0079u0079u0077, 2019_u0079u0079u0077, 2020_u0079u0079u0077, 2021_u0079u0079u0077"}'
      - key: g_database_temp
        value: 'phdatatemp'
      - key: g_database_input
        value: 'phdatacat'
    outputs:
      - key: g_out_price_city
        value: 'price_city'



