apiVersion: v1
kind: PhJob
metadata:
  name: job4_panel
  description: "pharbers job description"
  labels:
    name: job4_panel
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: project_name
        value: 'Takeda'
      - key: model_month_left
        value: '202001'
      - key: model_month_right
        value: '202012'
      - key: if_others
        value: 'False'
      - key: current_year
        value: '2021'
      - key: current_month
        value: '3'
      - key: monthly_update
        value: 'True'
      - key: add_47
        value: 'True'
      - key: out_path
        value: 's3://ph-platform/2020-11-11/etl/temporary_files/'
      - key: run_id
        value: 'run_id_max_test_2'
      - key: owner
        value: 'Airflow'
      - key: g_database_temp
        value: 'phdatatemp'
      - key: g_database_input
        value: 'phdatacat'
    outputs:
      - key: g_out_panel_result
        value: 'panel_result'



