apiVersion: v1
kind: PhJob
metadata:
  name: needclean
  description: "pharbers job description"
  labels:
    name: needclean
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: max_path
        value: 's3://ph-max-auto/v0.0.1-2020-06-08/'
      - key: project_name
        value: 'Empty'
      - key: outdir
        value: 'Empty'
      - key: minimum_product_sep
        value: '|'
      - key: minimum_product_columns
        value: 'Brand, Form, Specifications, Pack_Number, Manufacturer'
      - key: test
        value: 'False'
    outputs:
      - key: c
        value: 'abc'
      - key: d
        value: 'def'



