apiVersion: v1
kind: PhDag
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  description: "cpa_match"
  start_date: 1 # if you don't understand, don't touch it
  schedule_interval: "None" # if you don't understand, don't touch it
  dag_timeout: 60 # minutes
  email: ['airflow@example.com']
  email_on_failure: False
  email_on_retry: False
  retries: 1
  retry_delay: "minutes=5"
  owner: zyyin
  dag_id: BPBatchDAG
  dag_tag: BPBatchDAG
  jobs:
    - name: job1_distinct
      command: python3
    - name: job2_human_replace
      command: python3
    - name: job3_join
      command: python3
    - name: job4_edit_distance
      command: python3
    - name: job5_match
      command: python3
  linkage: "job1_distinct >> job2_human_replace >> job3_join >> job4_edit_distance >> job5_match"

