apiVersion: v1
kind: PhDag
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  description: "Pharbers Batch Process DAG"
  start_date: 1 # if you don't understand, don't touch it
  schedule_interval: "None" # if you don't understand, don't touch it
  dag_timeout: 60 # minutes
  email: ['airflow@example.com']
  email_on_failure: False
  email_on_retry: False
  retries: 1
  retry_delay: "minutes=5"
  owner: zyyin
  dag_id: BPBatchDAG
  dag_tag: BPBatchDAG
  jobs:
    - name: job1_distinct
      command: python
    - name: job2_join
      command: python
    - name: job3_edit_distance
      command: python
    - name: job4_match
      command: python
  linkage: "job1_distinct >> job2_join >> job3_edit_distance >> job4_match"

