apiVersion: v1
kind: PhJob
metadata:
  name: raw_data_mapping
  description: "pharbers job description"
  labels:
    name: raw_data_mapping
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 60.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: clean_input
        value: "s3a://ph-max-auto/2020-08-11/data_matching/refactor/data/MAX/TMP/RAW_DATA/"
      - key: time
        value: "2021-04-06"
      - key: company
        value: "贝达"
    outputs:
      - key: raw_data_output
        value: "s3a://ph-max-auto/2020-08-11/data_matching/refactor/data/MAX/FACT/RAW_DATA_FACT/"



