apiVersion: v1
kind: PhJob
metadata:
  name: job1
  description: "pharbers job description"
  labels:
    name: job1
    runtime: python3
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf.yaml
    args:
      - key: a
        value: 123
      - key: b
        value: 456
    outputs:
      - key: c
        value: abcde
      - key: d
        value: 6789



