apiVersion: v1
kind: PhJob
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf.yaml
    args:
      - key: run_id
        value: default
      - key: job_id
        value: default
      - key: version
        value: 2020-08-31
      - key: hor_measures_content_path
        value: s3a://ph-max-auto/2020-08-31/jobs/runId_5c92536e-9164-4d63-85c0-c03529669864/horcalmeasures/jobId_d06221d8-9c24-4b82-b546-5c6f1c2a261c/content
      - key: postgres_uri
        value: jdbc:postgresql://ph-db-lambda.cngk1jeurmnv.rds.cn-northwest-1.amazonaws.com.cn/phtestdb
      - key: postgres_user
        value: pharbers
      - key: postgres_pass
        value: Abcde196125
    outputs:
      - key: a
        value: abcde
      - key: b
        value: 6789
