apiVersion: v1
kind: PhJob
metadata:
  name: prediction_report
  description: "pharbers job description"
  labels:
    name: prediction_report
    runtime: python3
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf.yaml
    command: submit
    timeout: 600
    args:
      - key: training_data_path
        value: s3a://ph-max-auto/2020-08-11/data_matching/airflow_runs/1609843730/crossing/result_path/ad0bbdc1155f47a0949a4c
      - key: predictions_path
        value: s3a://ph-max-auto/2020-08-11/data_matching/airflow_runs/1609843730/prediction/result_path/0d85a90d71704bc6a8c2
      - key: split_data_path
        value: s3a://ph-max-auto/2020-08-11/data_matching/airflow_runs/1609843730/crossing/split_data_path/ad0bbdc1155f47a0949a4c
    outputs:
      - key: positive_result_path
        value: s3a://ph-max-auto/2020-08-11/data_matching/prediction_report/positive_result_path
      - key: negative_result_path
        value: s3a://ph-max-auto/2020-08-11/data_matching/prediction_report/negative_result_path
      - key: lost_data_path
        value: s3a://ph-max-auto/2020-08-11/data_matching/prediction_report/lost_data_path
      - key: positive_result_path_csv
        value: s3a://ph-max-auto/2020-08-11/data_matching/prediction_report/positive_result_path_csv
      - key: negative_result_path_csv
        value: s3a://ph-max-auto/2020-08-11/data_matching/prediction_report/negative_result_path_csv
      - key: lost_data_path_csv
        value: s3a://ph-max-auto/2020-08-11/data_matching/prediction_report/lost_data_path_csv
      - key: final_report_path
        value: s3a://ph-max-auto/2020-08-11/data_matching/prediction_report/final_report_path
