apiVersion: v1
kind: PhJob
metadata:
  name: check_general
  description: "pharbers job description"
  labels:
    name: check_general
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 1000.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: g_input_check
        value: '{"ims_sales_info":"run_id", "max_result_standard":"run_id"}'
      - key: g_check_standard
        value: '> 1.5'
      - key: run_id
        value: 'run_id_max_test'
      - key: project_name
        value: 'Takeda'
    outputs:
      - key: c
        value: 'abc'
      - key: d
        value: 'def'



