apiVersion: v1
kind: PhDag
metadata:
  name: extract_data
  description: "extract data"
  labels:
    name: extract_data
spec:
  description: "extract data"
  start_date: 1 # if you don't understand, don't touch it
  schedule_interval: "None" # if you don't understand, don't touch it
  dag_timeout: 60 # minutes
  email: ["pqian@pharbers.com"]
  email_on_failure: False
  email_on_retry: False
  retries: 1
  retry_delay: "minutes=5"
  owner: pqian
  dag_id: extract_data
  dag_tag: ExtractData
  jobs:
    - name: extract_data.extract
    - name: extract_data.copy
    - name: preset.write_asset
    - name: extract_data.email
  linkage:
    - "extract_data.extract >> extract_data.copy >> preset.write_asset >> extract_data.email"
