apiVersion: v1
kind: PhDag
metadata:
  name: job_customer_mapping
  description: "pharbers job description"
  labels:
    name: job_customer_mapping
    runtime: python3
spec:
  description: "customer mapping"
  start_date: 1 # if you don't understand, don't touch it
  schedule_interval: "None" # if you don't understand, don't touch it
  dag_timeout: 60 # minutes
  email: ['airflow@example.com']
  email_on_failure: False
  email_on_retry: False
  retries: 1
  retry_delay: "minutes=5"
  owner: zm
  dag_id: job_customer_mapping
  dag_tag: job_customer_mapping
  jobs:
    - name: job_customer_mapping
      command: python3
  linkage:
    - "job_customer_mapping"

