apiVersion: v1
kind: PhDag
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  description: "Create Hive Table And Email Notice DAG"
  start_date: 1 # if you don't understand, don't touch it
  schedule_interval: "None" # if you don't understand, don't touch it
  dag_timeout: 60 # minutes
  email: ['airflow@example.com']
  email_on_failure: False
  email_on_retry: False
  retries: 1
  retry_delay: "minutes=5"
  owner: clock
  dag_id: create_hive_table
  dag_tag: create_hive_table
  jobs:
    - name: create_hive_table
      command: python3
  linkage: "create_hive_table"

