apiVersion: v1
kind: PhJob
metadata:
  name: job7_raw_standard
  description: "pharbers job description"
  labels:
    name: job7_raw_standard
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: extract_path
        value: 's3://ph-platform/2020-11-11/etl/extract/rawdata_standard'
      - key: project_name
        value: 'Takeda'
      - key: if_two_source
        value: 'True'
      - key: minimum_product_sep
        value: '|'
      - key: minimum_product_columns
        value: 'Brand, Form, Specifications, Pack_Number, Manufacturer'
      - key: out_path
        value: 's3://ph-platform/2020-11-11/etl/temporary_files/'
      - key: run_id
        value: 'run_id_max_test'
      - key: owner
        value: 'Airflow'
      - key: g_input_version
        value: '{"cpa_pha_mapping_common":"20210623_u0079u0079u0077", "prod_mapping":"202103_u0079u0079u0077", "product_map_all_atc":"20210617", "master_data_map":"20210623_u0079u0079u0077", "province_city_mapping_common":"20210623_u0079u0079u0077", "mkt_mapping":"20210623_u0079u0079u0077", "universe_base_common":"2020_u0079u0079u0077", "raw_data":{"data":"202103_u0079u0079u0077", "data_std":"202103_u0079u0079u0077", "data_delivery":"202103_u0079u0079u0077"}}'
      - key: g_database_temp
        value: 'phdatatemp'
      - key: g_database_input
        value: 'phdatacat'
    outputs:
      - key: g_out_raw_standard
        value: 'rawdata_standard'
      - key: g_out_raw_standard_brief
        value: 'rawdata_standard_brief'



