apiVersion: v1
kind: PhJob
metadata:
  name: model_preditions
  description: "pharbers job description"
  labels:
    name: model_predictions
    runtime: python3
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf.yaml
    command: submit
    timeout: 800
    args:
      - key: job_name
        value: cleaning_data_model_predictions
      - key: path_prefix
        value: s3a://ph-max-auto/2020-08-11/data_matching/refactor/runs
      - key: final_prefix
        value: s3a://ph-max-auto/2020-08-11/data_matching/refactor/results
      - key: g_is_labeled
        value: 1
      - key: g_sharehold_mole_name
        value: 0.0
      - key: g_sharehold_product_name
        value: 0.1
      - key: g_sharehold_dosage
        value: 0.1
      - key: g_sharehold_spec
        value: 0.2
      - key: g_sharehold_manufacturer_name
        value: 0.5
      - key: g_sharehold_pack_qty
        value: 0.1
      - key: depend_job_names_keys
        value: 
          - cleaning_data_model_training#model_result#model
          - cleaning_data_model_training#data_of_features#input_data_of_features
          - cleaning_data_normalization#cleaning_origin#origin_data
          - cleaning_data_normalization#raw_table_of_no_exist_pack_check_id#input_df_of_no_pack_check_id
    outputs:
      - key: prediction_result
        value: prediction_result
      - key: positive_result
        value: positive_result
      - key: negative_result
        value: negative_result
      - key: final_predictions
        value: Predictions
      - key: final_positive
        value: Positive_Predictions
      - key: final_negative
        value: Negative_Predictions
      - key: final_lost
        value: Lost_Data
      - key: final_report
        value: Report
