apiVersion: v1
kind: PhJob
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf.yaml
    args:
      - key: out_path
        value: "s3a://ph-max-auto/2020-08-11/BPBatchDAG/pfizer_check/0.0.1"
      - key: in_prod_path
        value: "s3a://ph-stream/common/public/prod/0.0.15"
    outputs:
      - key: a
        value: abcde
      - key: b
        value: 6789

