apiVersion: v1
kind: PhJob
metadata:
  name: calculate_similarity_mole
  description: "pharbers job description"
  labels:
    name: calculate_similarity_mole
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 1200.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: job_name
        value: calculate_similarity_mole
      - key: path_prefix
        value: s3a://ph-max-auto/2020-08-11/data_matching/refactor/runs
      - key: depend_job_names_keys
        value:
        - segmentation_mole#segmentation_mole_result#input_seg_mole
      - key: g_repartition_shared
        value: 16
    outputs:
      - key: similarity_mole_result
        value: similarity_mole_result



