apiVersion: v1
kind: PhJob
metadata:
  name: packaging
  description: "提数副本打包存入s3"
  labels:
    name: packaging
    runtime: python3
    command: script
spec:
  containers:
    repository: local
    runtime: python3
    command: script
    timeout: 60.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: from
        value: default_from
      - key: out_suffix
        value: default_to
    outputs:
      - key: c
        value: "abc"
