apiVersion: v1
kind: PhDag
metadata:
  name: atc_code_match
  description: "atc_code_match"
  labels:
    name: atc_code_match
    runtime: python3
spec:
  description: "A Max Auto Job Example"
  start_date: 1 # if you don't understand, don't touch it
  schedule_interval: "None" # if you don't understand, don't touch it
  dag_timeout: 60 # minutes
  email: ['airflow@example.com']
  email_on_failure: False
  email_on_retry: False
  retries: 1
  retry_delay: "minutes=5"
  owner: zm
  dag_id: atc_code_match
  dag_tag: atc_code_match
  jobs:
    - name: atc_code_match
      command: python3
  linkage:
    - "atc_code_match"

