apiVersion: v1
kind: PhJob
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf.yaml
    args:
      - key: max_path
        value: "s3a://ph-max-auto/v0.0.1-2020-06-08/"
      - key: project_name
        value: "Test/AZ"
      - key: out_path
        value: "s3a://ph-max-auto/v0.0.1-2020-06-08/"
      - key: out_dir
        value: "outlier"
      - key: panel_path
        value: "s3a://ph-max-auto/v0.0.1-2020-06-08/Test/AZ/panel-result_AZ_Sanofi"
      - key: universe_path
        value: "s3a://ph-max-auto/v0.0.1-2020-06-08/AZ/universe_az_sanofi_mch"
      - key: doi
        value: "AZ16"
      - key: product_input
        value: "普米克令舒,Others-Pulmicort,益索"
      - key: model_month_left
        value: "201901"
      - key: model_month_right
        value: "201911"
      - key: arg_year
        value: "2019"
    outputs:
      - key: a
        value: abcde
      - key: b
        value: 6789

