apiVersion: v1
kind: PhJob
metadata:
  name: alfred
  description: "pharbers job description"
  labels:
    name: alfred
spec:
  containers:
    repository: local
    runtime: python3
    code: phmain.py
    config: phconf.yaml
    args:
      - key: input_path
        value: s3a://ph-stream/common/public/cpa/0.0.22
      - key: cpa_prod_path
        value: s3a://ph-platform/2020-08-10/datamart/original/dimensions/cpa_prods/v0.0.22_20201020_1
      - key: cpa_hosp_path
        value: s3a://ph-platform/2020-08-10/datamart/original/dimensions/cpa_hosps/v0.0.22_20201020_1
      - key: cpa_date_path
        value: s3a://ph-platform/2020-08-10/datamart/original/dimensions/cpa_dates/v0.0.22_20201020_1
      - key: cpa_etc_path
        value: s3a://ph-platform/2020-08-10/datamart/original/dimensions/cpa_etc/v0.0.22_20201020_1
      - key: output_path
        value: s3a://ph-platform/2020-08-10/datamart/original/fact_tables/cpa/v0.0.22_20201020_1
    outputs:
      - key: a
        value: abcde
      - key: b
        value: 6789



