apiVersion: v1
kind: PhJob
metadata:
  name: rawdata_shanghai
  description: "pharbers job description"
  labels:
    name: rawdata_shanghai
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 10.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: g_sh_method
        value: 'full'
      - key: b
        value: '456'
    outputs:
      - key: g_sh_method
        value: 'full'
      - key: d
        value: 'def'



