apiVersion: v1
kind: PhJob
metadata:
  name: job2
  description: "pharbers job description"
  labels:
    name: job2
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 10.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: project_path
        value: s3a://a/b/c
      - key: parent_path
        value: /airflow_runs/
      - key: run_id_path
        value: run_id_path
      - key: split_data_path
        value: /crossing/split_data_path/
      - key: job_id_path
        value: job_id
    outputs:
      - key: output_path
        value: s3a://a/b/c/



