apiVersion: v1
kind: PhJob
metadata:
  name: ntmassessment
  description: "pharbers job description"
  labels:
    name: ntmassessment
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 10.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: job_name
        value: ntmassessment
      - key: path_prefix
        value: s3a://ph-max-auto/2020-08-11/NTM/runs
      - key: depend_job_names_keys
        value: 
          - ntmcal#cal_result#cal_path
          - ntmcompetitor#competitor_result#competitor_path
       - key: provider
        value: NTM
      - key: proposal_id
        value: 60505e4b81ef2c5db38b4699
      - key: project_id
        value: rR9lwp8e55q9izZdHdQZ
      - key: period_id
        value: o8mpVPkJTVrUFfgk6KR-
      - key: phase
        value: 1         
      - key: standard_time_path
        value: s3a://ph-max-auto/2020-08-11/NTM/data/Standard_Time.csv
      - key: level_data_path
        value: s3a://ph-max-auto/2020-08-11/NTM/data/Level.csv4"
    outputs:
      - key: assessment_result
        value: assessment_result
