apiVersion: v1
kind: PhJob
metadata:
  name: job1_hospital_mapping
  description: "pharbers job description"
  labels:
    name: job1_hospital_mapping
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 720.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: project_name
        value: 'Takeda'
      - key: if_others
        value: 'False'
      - key: out_path
        value: 's3://ph-platform/2020-11-11/etl/temporary_files/'
      - key: run_id
        value: 'run_id_max_test'
      - key: owner
        value: 'Airflow'
      - key: g_input_version
        value: '{"raw_data":{"data":"202103_u0079u0079u0077"}, "universe_base":"2020_u0079u0079u0077", "cpa_pha_mapping":"20210623_u0079u0079u0077"}'
    outputs:
      - key: g_out_table
        value: 'hospital_mapping_out'



