apiVersion: v1
kind: PhJob
metadata:
  name: calculate_similarity_mnf
  description: "pharbers job description"
  labels:
    name: calculate_similarity_mnf
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 1200.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: job_name
        value: calculate_similarity_mnf
      - key: path_prefix
        value: s3a://ph-max-auto/2020-08-11/data_matching/refactor/runs
      - key: depend_job_names_keys
        value:
        - mapping_mnf#mapping_mnf_result#input_mapping_mnf
      - key: g_repartition_shared
        value: 16
    outputs:
      - key: similarity_mnf_result
        value: similarity_mnf_result



