apiVersion: v1
kind: PhJob
metadata:
  name: get_table_of_pack_check_id_not_exist
  description: "pharbers job description"
  labels:
    name: get_table_of_pack_check_id_not_exist
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 10.0
    code: phmain.py
    config: phconf.yaml
    args:
     - key: job_name
       value: get_table_of_pack_check_id_not_exist
     - key: path_prefix
       value: s3a://ph-max-auto/2020-08-11/data_matching/refactor/runs
     - key: depend_job_names_keys
       value: 
         - get_correct_data#output_correct_result#input_correct_table
    outputs:
      - key: table_of_no_check_id_in_standard_csv
        value: table_of_no_check_id_in_standard_csv



