apiVersion: v1
kind: PhJob
metadata:
  name: cpa_pha_mapping_by_common_file
  description: "pharbers job description"
  labels:
    name: cpa_pha_mapping_by_common_file
    runtime: python3
    command: submit
spec:
  containers:
    repository: local
    runtime: python3
    command: submit
    timeout: 60.0
    code: phmain.py
    config: phconf.yaml
    args:
      - key: cpa_pha_mapping_input
        value: "s3://ph-max-auto/v0.0.1-2020-06-08/Common_files/cpa_pha_mapping"
      - key: version
        value: "0.0.1"
      - key: company
        value: "PHARBERS"
      - key: label
        value: ""
    outputs:
      - key: cpa_pha_mapping_output
        value: "s3://ph-max-auto/2020-08-11/data_matching/refactor/data/MAX/REFACTOR/MAPPING/CODE_MAPPING"



